### ISSUE TITLE
React-iOS- Bridging

### ISSUE THREAD

**Issue by aakivb** [SattiSriramiOS/React-Native-LocalNotifications#1]
Sriram,

Can you please modify this code to support React-ObjectiveC/Swift bridging ?

We need the UI to be on React and Code for local notifications on ObjectiveC, Please correct the code and revert us back.

**Comment by Satti-Sriram** [comment]
Aakiv,

      I have made another React Project without expo. As you said. Please Check out [here](https://github.com/SattiSriramiOS/RCTPush-Objective-C).
